# Generated by Django 5.2.15 on 2026-06-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('owner', models.CharField(max_length=80)),
                ('channel', models.CharField(choices=[('blog', 'Blog post'), ('webinar', 'Webinar'), ('newsletter', 'Newsletter'), ('social', 'Social campaign'), ('case-study', 'Case study')], default='blog', max_length=20)),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('writing', 'Writing'), ('review', 'In review'), ('scheduled', 'Scheduled'), ('live', 'Live')], default='backlog', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('due_date', models.DateField()),
                ('is_featured', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('due_date', '-is_featured', 'title'),
            },
        ),
    ]
